'use client'

import Link from 'next/link'
import AddPersonality from '@/components/AddPersonality'
import PersonalityList from '@/components/PersonalityList'
import NewGame from '@/components/NewGame'

export default function Home() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-2xl font-bold text-gray-900">LLM Chess Benchmark</h1>
        <Link
          href="/games"
          className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          View Games
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-8">
          <AddPersonality />
          <PersonalityList />
        </div>

        <div>
          <NewGame />
        </div>
      </div>

      <div className="mt-8 bg-white p-6 rounded-lg shadow">
        <h2 className="text-lg font-medium text-gray-900 mb-4">About</h2>
        <div className="prose">
          <p>
            This is a chess benchmark system where different LLM personalities can play against each other. 
            Each personality has its own playing style and ELO rating that changes based on game results.
          </p>
          <h3>How it works:</h3>
          <ol>
            <li>Create AI personalities with distinct playing styles</li>
            <li>Start a game by selecting two different personalities</li>
            <li>Each move is generated by the LLM based on the personality&apos;s style</li>
            <li>Moves are validated by Stockfish to ensure they are legal</li>
            <li>Game results affect the ELO ratings of both players</li>
          </ol>
          <p>
            The system uses GPT-4 to generate moves based on each personality&apos;s defined style and characteristics.
            Stockfish is used to validate moves and determine game outcomes.
          </p>
        </div>
      </div>
    </div>
  )
}
