export interface LLMResponse {
  move: string
  reasoning?: string
}

import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions'

export interface LLMProvider {
  chat(messages: ChatCompletionMessageParam[], options?: any): Promise<string>
}

// OpenAI Provider
export class OpenAIProvider implements LLMProvider {
  constructor(private apiKey: string) {}

  async chat(messages: ChatCompletionMessageParam[], options?: any): Promise<string> {
    const OpenAI = (await import('openai')).default
    const openai = new OpenAI({ apiKey: this.apiKey })

    const response = await openai.chat.completions.create({
      model: options?.model || "gpt-4",
      messages: messages as any, // Type assertion needed due to OpenAI SDK typing issue
      temperature: options?.temperature || 0.7,
      response_format: { type: "json_object" }
    })

    return response.choices[0].message.content || ''
  }
}

// Default provider that uses Stockfish as fallback
export class StockfishProvider implements LLMProvider {
  async chat(messages: ChatCompletionMessageParam[], options?: any): Promise<string> {
    // Extract FEN from the messages
    const userMessage = messages.find(m => m.role === 'user')?.content
    if (!userMessage || typeof userMessage !== 'string') {
      throw new Error('Invalid message content')
    }
    const fenMatch = userMessage.match(/Current position \(FEN\): (.+)/)
    if (!fenMatch) throw new Error('FEN not found in message')
    
    const fen = fenMatch[1]
    
    // Use server-side Stockfish
    const { getNextMove } = await import('../utils/server/stockfish')
    const move = await getNextMove(fen)
    
    return JSON.stringify({
      move,
      reasoning: "Move generated by Stockfish engine"
    })
  }
}

export async function generateMove(
  personality: {
    name: string
    description: string
    provider?: {
      type: string
      config?: any
    }
  },
  fen: string,
  pgn: string,
  isWhite: boolean
): Promise<LLMResponse> {
  // Initialize provider based on personality configuration
  let provider: LLMProvider
  if (personality.provider?.type === 'openai' && personality.provider.config?.apiKey) {
    provider = new OpenAIProvider(personality.provider.config.apiKey)
  } else {
    // Default to Stockfish if no valid provider configured
    provider = new StockfishProvider()
  }
  const prompt = `You are ${personality.name}, a chess player with the following style: ${personality.description}

Current position (FEN): ${fen}
Game moves so far (PGN): ${pgn}
You are playing as ${isWhite ? 'White' : 'Black'}

Analyze the position and provide your next move in standard algebraic notation (e.g. e4, Nf3, O-O).
Consider your playing style and explain your reasoning.

Respond in JSON format:
{
  "move": "your move in algebraic notation",
  "reasoning": "your explanation for the move"
}`

  try {
    const response = await provider.chat([
      {
        role: "system",
        content: "You are a chess engine that generates moves based on a given personality and position. Respond only with valid chess moves in the requested JSON format."
      },
      {
        role: "user",
        content: prompt
      }
    ], personality.provider?.config)

    const result = JSON.parse(response)
    
    if (!result.move) {
      throw new Error('No move generated')
    }

    return result
  } catch (error) {
    console.error('Error generating move:', error)
    throw error
  }
}
